### ISSUE TITLE
No egg configuration was defined for this egg

### ISSUE THREAD

**Issue by jakub96124124** [JPylypiw/teamspeak-egg#1]
No egg configuration was defined for this egg 
problem start server

**Comment by jp1337** [comment]
Oh hey :)
I am sorry, I completely forgot to answer on this issue.
Can you provide more information about your problem?
At the first thoughts you maybe have forgot to restart the wings service after importing the egg.
This is nessesary to copy the egg information to the wings daemon.

**Comment by jp1337** [comment]
No reponse, I think this is solved.
