### ISSUE TITLE
[Bug] with using mariaDB

### ISSUE THREAD

**Issue by Wunderharke** [JPylypiw/teamspeak-egg#2]
I'm using this egg and had to search a lot to get mariaDB working.
Solution can be found here:
https://github.com/pterodactyl/panel/issues/630

maybe this shoud be meged ihto here.

**Comment by jp1337** [comment]
Hi @Wunderharke,
sorry I noticed the issue very late...
Sure I can implement this in the egg while installing.
When I got all information right I only need to copy the libmariadb.so.2 from the redist folder to the root folder.
Am I right with that?

**Comment by Wunderharke** [comment]
Hi @jpylypiw,

I haven't tried that, however, that should work as well.
I simply added 
`export LD_LIBRARY_PATH=".:redist:$LD_LIBRARY_PATH"`
at top of ts3server_minimal_runscript.sh.
